name: "Continuous Integration"

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        composer-dependencies:
          - highest
          - lowest
          - locked
        operating-system:
          - ubuntu-latest
          - windows-latest
        php-versions:
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl, sodium, zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v7
      - uses: ramsey/composer-install@v4
        with:
          dependency-versions: ${{ matrix.composer-dependencies }}
      - name: GH token
        run: composer config --global --auth github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
      - name: Run PHPUnit
        run: vendor/bin/phpunit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  coding-standards:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: intl, sodium, zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v7
      - uses: ramsey/composer-install@v4
      - name: Run PHPCS
        run: vendor/bin/phpcs

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: intl, sodium, zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v7
      - uses: ramsey/composer-install@v4
      - name: Validate the composer configuration
        run: composer validate --strict
      - name: Run PHPStan
        run: vendor/bin/phpstan

  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: intl, sodium, zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v7
      - uses: ramsey/composer-install@v4
      - run: |
          ./bin/cli.php verify-bundle \
            --bundle=test/fixture/bundle.json \
            --certificate-identity=https://github.com/php/pie/.github/workflows/build-phar.yml@refs/tags/1.2.0 \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
            test/fixture/pie.phar

  sigstore-conformance:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl, sodium, zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v7
      - uses: ramsey/composer-install@v4
      - uses: sigstore/sigstore-conformance@21533cde107c734ebc153c3e3a24d75fc9811a36 # v0.0.29
        with:
          entrypoint: ${{ github.workspace }}/bin/cli.php
          skip-signing: "true"
          skip-result-upload: "true" # we can enable this when closer to completion
          xfail: |
            test_verify[[]DIGEST-rekor2-timestamp-without-embedded-cert]
            test_verify[[]DIGEST-rekor2-checkpoint-two-sigs-cosigned]
            test_verify[[]DIGEST-rekor2-timestamp-with-expired-cert-chain]
            test_verify[[]DIGEST-rekor2-checkpoint-multiple-cosigs]
            test_verify[[]DIGEST-rekor2-happy-path]
            test_verify[[]DIGEST-rekor2-checkpoint-cosigned]
            test_verify[[]DIGEST-rekor2-checkpoint-two-sigs-from-origin]
            test_verify[[]DIGEST-rekor2-checkpoint-origin-not-first]
            test_verify[[]DIGEST-rekor2-timestamp-with-embedded-cert]

            test_verify[[]DIGEST-trust-root-tsa-validity-end-inclusive]


            test_verify[[]PATH-managed-key-happy-path]
            test_verify[[]PATH-managed-key-and-trusted-root]
            test_verify[[]DIGEST-managed-key-happy-path]
            test_verify[[]DIGEST-managed-key-and-trusted-root]

            test_verify[[]DIGEST-happy-path-v0.1]
            test_verify[[]DIGEST-happy-path-v0.2]
            test_verify[[]DIGEST-happy-path-v0.3]
            test_verify[[]DIGEST-happy-path-v0.3-new-mediaType]
            test_verify[[]DIGEST-bundle-with-sct-with-extensions]
            test_verify[[]DIGEST-trust-root-tlog-validity-end-inclusive]

            test_verify[[]PATH-rekor2-timestamp-payload-mismatch_fail]
            test_verify[[]PATH-rekor2-no-timestamp_fail]
            test_verify[[]PATH-rekor2-dsse-mismatch-sig_fail]
            test_verify[[]PATH-rekor2-dsse-mismatch-envelope_fail]
            test_verify[[]DIGEST-rekor2-dsse-mismatch-sig_fail]
            test_verify[[]DIGEST-rekor2-dsse-mismatch-envelope_fail]
